services:
  pfdb:
    image: bianjp/mariadb-alpine:latest
    container_name: "$MYSQL_HOST"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MARIADB_DISABLE_UPGRADE_BACKUP: 1
      MARIADB_AUTO_UPGRADE: 1
    networks:
      - pf
    volumes:
      - db_data:/var/lib/mysql
      - ./pathfinder/export/sql/eve_universe.sql.zip:/eve_universe.sql.zip
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
  pf-redis:
    image: redis:6.2.5-alpine3.14
    command: ["redis-server", "--appendonly", "yes"]
    container_name: "$REDIS_HOST"
    networks:
      - pf
    volumes:
      - redis_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"
    restart: always
  pf-socket:
    image: ghcr.io/goryn-clade/pf-websocket:latest
    command: ["--tcpHost", "0.0.0.0"]
    container_name: "$PATHFINDER_SOCKET_HOST"
    networks:
      - pf
    volumes:
      - ./logs:/var/www/html/pathfinder/history/map
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
  pf:
    container_name: pathfinder
    image: ghcr.io/goryn-clade/pathfinder:latest
    env_file:
      - .env
    networks:
      - pf
    ports:
      - "127.0.0.1:80:80"
    healthcheck:
      disable: true
    volumes:
      - ./config/pathfinder/config.ini:/var/www/html/pathfinder/app/templateConfig.ini
      - ./config/pathfinder/pathfinder.ini:/var/www/html/pathfinder/app/pathfinder.ini
      - ./config/pathfinder/plugin.ini:/var/www/html/pathfinder/app/plugin.ini
      - ./logs:/var/www/html/pathfinder/history/map
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - pfdb
      - pf-redis
      - pf-socket
    restart: always

volumes:
  db_data:
  redis_data:
networks:
  pf:
